"""empty message

Revision ID: c34aad6be4af
Revises: ec6041d7f08e
Create Date: 2019-04-01 10:43:12.085761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c34aad6be4af'
down_revision = 'ec6041d7f08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', sa.String(length=100), nullable=True))
    op.drop_column('admin', 'pwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('pwd', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###
